### ISSUE TITLE
Some errors happened!!!

### ISSUE THREAD

**Issue by kkxLly** [wang-chen/KCC#1]
I tested KCC on benchmark and when i run main_running got a error that the index is equial to array's nums.
So, if you have some idea about it, please contact me!

**Comment by wang-chen** [comment]
It will be easier for me to help you if you can show more information about the error.

**Comment by kkxLly** [comment]
> It will be easier for me to help you if you can show more information about the error.

Thanks your reply! i have solved it by google!!! 
Looking forward to your new idea about CF！
